### ISSUE TITLE
Responder to change template variable

### ISSUE THREAD

**Issue by mpadge** [ropensci-org/buffy#26]
@xuanxu The [multiple approve commands](https://github.com/ropensci-org/buffy/issues/20) mean that we've got a new `"statsgrade"` variable in one of our templates. Would it be possible to add a responder which could change the value of that variable?

**Comment by maelle** [comment]
and that probably _adds_ the variable if missing? We can't guarantee template integrity yet. :sweat_smile:

**Comment by mpadge** [comment]
> and that probably _adds_ the variable if missing? We can't guarantee template integrity yet. sweat_smile

Yes indeed, as an extension of #14

**Comment by xuanxu** [comment]
There is already a standard responder to change the value of a variable in the body of the issue, the [SetValueResponder](https://buffy.readthedocs.io/en/latest/responders/set_value.html). It can be configured to add the variable (appending or prepending) to the issue with the `if_missing`. Sample config:
```yml
set_value:
  - statsgrade:
      only: editors
      sample_value: "gold"
      if_missing: append
      heading: "Badge grade" 
```

With that config the command `@reviewer_bot set silver as statsgrade` should update or add the value.
