### ISSUE TITLE
Is ropensci/software-review hard-coded somewhere

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#62]
I opened an issue in https://github.com/ropenscilabs/statistical-software-review/issues/30

provoking a response in https://github.com/ropensci/software-review/issues/30

**Comment by maelle** [comment]
Pinging @xuanxu @mpadge

**Comment by maelle** [comment]
ah yes! https://github.com/ropensci-org/buffy/blob/a61112d8de7ae2fa0e08d1896a8a6c175a54c58e/config/settings-production.yml#L33

**Comment by maelle** [comment]
Could the repo be filled by buffy instead, based on the info in the webhook payloads?

**Comment by maelle** [comment]
So maybe for the test repo I should use... the testing config :grin:

**Comment by xuanxu** [comment]
The [current config](https://github.com/ropensci-org/buffy/blob/ropensci/config/settings-production.yml#L28-L37) for that external call is:
```yaml
external_service:
        name: editorcheck
        url: http://138.68.123.59:8000/editorcheck
        method: get
        query_params:
          repo: ropensci/software-review
        data_from_issue:
          - repourl
          - issue_id
        template_file: goodpractice.md
```

That seems wrong because the repo is being hardcoded but also the `repourl` is an invalid key for [data_from_issue](https://buffy-ropensci.readthedocs.io/en/latest/responders/external_service.html#params), so I think that config is calling the following url: 
`http://138.68.123.59:8000/editorcheck?repo=ropensci/software-review&repourl=&issue_id=23`

But I guess what needs to be called is: 
`http://138.68.123.59:8000/editorcheck?repo=ropensci/software-review&issue_id=23` 
with both `repo` and `issue_id` extracted dinamically. So, the config should be simplyfied to:

```yaml
external_service:
        name: editorcheck
        url: http://138.68.123.59:8000/editorcheck
        method: get
        data_from_issue:
          - repo
          - issue_id
        template_file: goodpractice.md
```
